/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as VendasIndexRouteImport } from './routes/vendas.index'
import { Route as VendasEncerradasRouteImport } from './routes/vendas.encerradas'
import { Route as VendasVendaIdLancarRouteImport } from './routes/vendas.$vendaId.lancar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasIndexRoute = VendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasEncerradasRoute = VendasEncerradasRouteImport.update({
  id: '/vendas/encerradas',
  path: '/vendas/encerradas',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasVendaIdLancarRoute = VendasVendaIdLancarRouteImport.update({
  id: '/vendas/$vendaId/lancar',
  path: '/vendas/$vendaId/lancar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/vendas/encerradas': typeof VendasEncerradasRoute
  '/vendas/': typeof VendasIndexRoute
  '/vendas/$vendaId/lancar': typeof VendasVendaIdLancarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/vendas/encerradas': typeof VendasEncerradasRoute
  '/vendas': typeof VendasIndexRoute
  '/vendas/$vendaId/lancar': typeof VendasVendaIdLancarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/vendas/encerradas': typeof VendasEncerradasRoute
  '/vendas/': typeof VendasIndexRoute
  '/vendas/$vendaId/lancar': typeof VendasVendaIdLancarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/clientes'
    | '/financeiro'
    | '/pedidos'
    | '/produtos'
    | '/vendas/encerradas'
    | '/vendas/'
    | '/vendas/$vendaId/lancar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/clientes'
    | '/financeiro'
    | '/pedidos'
    | '/produtos'
    | '/vendas/encerradas'
    | '/vendas'
    | '/vendas/$vendaId/lancar'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/clientes'
    | '/financeiro'
    | '/pedidos'
    | '/produtos'
    | '/vendas/encerradas'
    | '/vendas/'
    | '/vendas/$vendaId/lancar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  ClientesRoute: typeof ClientesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  VendasEncerradasRoute: typeof VendasEncerradasRoute
  VendasIndexRoute: typeof VendasIndexRoute
  VendasVendaIdLancarRoute: typeof VendasVendaIdLancarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/': {
      id: '/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof VendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/encerradas': {
      id: '/vendas/encerradas'
      path: '/vendas/encerradas'
      fullPath: '/vendas/encerradas'
      preLoaderRoute: typeof VendasEncerradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/$vendaId/lancar': {
      id: '/vendas/$vendaId/lancar'
      path: '/vendas/$vendaId/lancar'
      fullPath: '/vendas/$vendaId/lancar'
      preLoaderRoute: typeof VendasVendaIdLancarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  ClientesRoute: ClientesRoute,
  FinanceiroRoute: FinanceiroRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  VendasEncerradasRoute: VendasEncerradasRoute,
  VendasIndexRoute: VendasIndexRoute,
  VendasVendaIdLancarRoute: VendasVendaIdLancarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
